version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.diffdock-fastapi
    container_name: diffdock-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app:/app/results/user_inference
    environment:
      - ENV_NAME=mydiffdock
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              count: all
    command: ["micromamba", "run", "-n", "mydiffdock", "uvicorn", "diffdock_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  app: